version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
    - echo Build completed on `date`
    - mvn clean
    - mvn validate
  test:
    commands:
    - echo Build completed on `date`
    - mvn test
  post_build:
    commands:
    - echo Build completed on `date`
    - mvn package
    - mv target/*.war helloworld.war
artifacts:
  files:
  - helloworld.war