version: 0.2
phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
    - mvn clean
    - mvn validate
    - echo Pre-build completed on 'data'
  build:
    commands:
    - echo Build completed on `date`
    - mvn compile
    - mvn test
  post_build:
    commands:
    - echo Build completed on `date`
    - mvn package
    - mv target/*.war helloworld.war
artifacts:
  files:
  - helloworld.war